### ISSUE TITLE
Create a helm chart for event router

### ISSUE THREAD

**Issue by timothysc** [heptiolabs/eventrouter#22]
see subject. 

/cc @rosskukulinski @kensimon

**Comment by baldwinSPC** [comment]
@timothysc @rosskukulinski @kensimon can anyone grab this issue or ...? we can knock this out pretty fast.

**Comment by rosskukulinski** [comment]
@baldwinSPC I need a break from reading training materials and have been looking for an excuse to learn Helm.  I can take it.

**Comment by timothysc** [comment]
@rosskukulinski the yaml in the repo probably needs a minor muck to be a chart.

**Comment by rosskukulinski** [comment]
My thought exactly - shouldn't be too many templated parameters.

**Comment by baldwinSPC** [comment]
cool. happy to assist where we can.

**Comment by rimusz** [comment]
@rosskukulinski ping me if you need any assistance/help, happy to help there

**Comment by rosskukulinski** [comment]
Draft here: https://github.com/rosskukulinski/charts/tree/eventrouter

I still need to cleanup the README - I'll tackle that tomorrow and open a PR for feedback.

**Comment by timothysc** [comment]
thx @rosskukulinski !

**Comment by rosskukulinski** [comment]
@timothysc @rimusz @baldwinSPC Feedback welcome: https://github.com/kubernetes/charts/pull/1023

**Comment by timothysc** [comment]
Closing.

**Comment by coffeepac** [comment]
in case anyone comes looking, we wrote a chart for this:  https://github.com/samsung-cnct/chart-eventrouter
