### ISSUE TITLE
Currently does not work with GKE from client-side

### ISSUE THREAD

**Issue by ahmetb** [heptiolabs/eventrouter#31]
If kubeconfig contains "gcp" auth provider, it won't work because

    import _ "k8s.io/client-go/plugin/pkg/client/auth/gcp"

and its dependencies are needed.

**Comment by timothysc** [comment]
Is this still an issue?  
we only submit via .yaml now

**Comment by ahmetb** [comment]
Yeah I think it is still an issue for those doing a `go build` and running eventrouter on their laptops.

This is because when client-go detects active kubeconfig is an gcp credential, it knows that it should run `gcloud` command to retrieve a fresh token.

However, if users create a google service account key and deliver to the eventrouter container with `GOOGLE_APPLICATION_CREDENTIALS` env var and deploy the eventrouter to Kubernetes (instead of doing a `go build` or `go run`)  it'll work fine.

Can be closed tbh, not sure if anyone else is using this on GKE. (GKE actually exports our events to Stackdriver –the monitoring product of Google Cloud).

**Comment by timothysc** [comment]
Yeah I switched the default build+deploy+to be containerized by default to make it clear.  

I'll close this one, thx for the feedback!
