### ISSUE TITLE
File output sink?

### ISSUE THREAD

**Issue by sokoow** [heptiolabs/eventrouter#52]
Hi All,

Very cool project. One thing I'd find useful would be a file sink, so I can then follow files in Splunk. Would this be a much to do ? Also, if you've no time, I'd like to write it - how do I even start ?

**Comment by SEJeff** [comment]
@sokoow you can just have splunk hoover up `/var/log/containers/eventrouter*`. We do this with our on-premise splunk + k8s and it works just fine. We use the glog sync and it logs to stdout for the eventrouter logs.

**Comment by queimadus** [comment]
How do you guys deal with files in `var/log/containers` being symlinks (to `/var/log/pods` and to `/var/lib/docker/containers`)?

@SEJeff do you mount all these directories inside your splunk container for it to hoover?

**Comment by SEJeff** [comment]
@queimadus we simply install and config splunk in the host operating system without a container. It would be trivial enough to volume mount those directories into a container if you're running on a host operating system such as Fedora CoreOS / Container Linux / RHEL Atomic Host however.

**Comment by johnSchnake** [comment]
@SEJeff thanks for the comments on this. @sokoow have you gotten what you needed? Closing but feel free to reopen if not.
