### ISSUE TITLE
Easier Elasticsearch Indexing

### ISSUE THREAD

**Issue by f0** [heptiolabs/eventrouter#56]
Currently the sink output looks like this:

`I0316 18:06:16.068912       7 glogsink.go:42] {"verb":"UPDATED","event":{"metadata":{"name":"curator-1521158460-pn977.151c3d919e2cc527","namespace":"es-extern",....`

is there a way to remove the `I0316 18:06:16.068912       7 glogsink.go:42] from the logline , this would make the indexing in  Elasticsearch  much easier

**Comment by pieterlange** [comment]
use the stdout sink.

**Comment by f0** [comment]
@pieterlange  thx
