### ISSUE TITLE
JSON namespacing

### ISSUE THREAD

**Issue by Godley** [heptiolabs/eventrouter#57]
Is there any way to configure the output of eventrouter so that it namespaces events, e.g wrap every output in `{'eventrouter': {<all fields in here>}}`? 

We manage our elasticsearch indexes using a company-wide index template and having it properly namespaced (preferably in a configurable way, i.e we'd be able to pass in what it wraps the json object in) would help to ensure the event related fields don't get mistakenly used for other purposes.

**Comment by pieterlange** [comment]
FWIW i let the eventrouter log to stdout (which is captured by fluentd) and then i can namespace on the runtime environment.

**Comment by Godley** [comment]
That’s interesting, we have the same setup so guess I can get fluentd to do some magic there.

**Comment by Godley** [comment]
having discussed this internally we decided the least hacky way to handle this was to attempt to add it ourselves - don't want to change the global fluentd + other options involved copious bash hackery.
