### ISSUE TITLE
Helm Chart available?

### ISSUE THREAD

**Issue by bjornmagnusson** [heptiolabs/eventrouter#59]
Is there any helm chart available for this? Would be very useful

**Comment by timothysc** [comment]
@bjornmagnusson , I believe @rosskukulinski created one, but I don't know where the PR ended.

**Comment by rosskukulinski** [comment]
My original PR timed out due to ETOOMANYTHINGS (https://github.com/kubernetes/charts/pull/1023), but it looks like someone submitted a new PR two weeks ago: https://github.com/kubernetes/charts/pull/5390

**Comment by bjornmagnusson** [comment]
Looks like it has been merged now :)
