### ISSUE TITLE
Can we have the latest master as a new release?

### ISSUE THREAD

**Issue by sukhong** [heptiolabs/eventrouter#92]
The latest release (v0.2) seems to be a little outdated, and we would like to have the latest master as v0.3 if possible.

**Comment by blakeroberts-wk** [comment]
@johnSchnake is this possible?

**Comment by johnSchnake** [comment]
Yes; sorry for the delay. I will work on getting a release out early this coming week.

**Comment by johnSchnake** [comment]
So two PRs are outstanding and one of them is a bugfix I'd like to get in before a release is cut. See #94 and #96 .  Will try and wait to see if those can get in without delaying this much further.

**Comment by blakeroberts-wk** [comment]
@johnSchnake any update on the schedule of the next release?

**Comment by johnSchnake** [comment]
Released! Sorry it took so long to get that out.
